# Generated by Django 2.0.5 on 2018-05-30 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Название товара', max_length=40)),
                ('subtitle', models.CharField(default='Краткое описание', max_length=40)),
                ('discriotion', models.TextField(default='Описание товара')),
                ('price', models.CharField(default='Цена(просто число)', max_length=10)),
                ('isdiscount', models.CharField(choices=[('1', 'да'), ('2', 'нет')], max_length=3, verbose_name='нет')),
                ('Category', models.CharField(choices=[('1', 'Мягкая мебель'), ('2', 'Гостиная'), ('3', 'Спальня'), ('4', 'Кухня'), ('5', 'Столовая'), ('6', 'Прихожая'), ('7', 'Ванная'), ('8', 'Детская'), ('9', 'Рабочий кабинет')], default='Мягкая мебель', max_length=20, verbose_name='Категория')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('image1', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('image5', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('image6', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('image7', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('image8', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('inCollection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Collection')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.shops')),
            ],
        ),
    ]
