# Generated by Django 2.0.5 on 2018-06-24 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainpage', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Название товара')),
                ('subtitle', models.CharField(max_length=40, verbose_name='Краткое описание')),
                ('discriotion', models.TextField(verbose_name='Описание товара')),
                ('size', models.CharField(default='Не отображать', max_length=40, verbose_name='Размеры')),
                ('matherial', models.CharField(default='Не отображать', max_length=40, verbose_name='Материал')),
                ('color', models.CharField(default='Не отображать', max_length=40, verbose_name='Цвета')),
                ('qualities', models.TextField(default='Не отображать', verbose_name='Доп. характеристики')),
                ('price', models.FloatField(default=0.0, verbose_name='Цена')),
                ('isdiscount', models.BooleanField(default=False, verbose_name='На скидке?')),
                ('newprice', models.FloatField(default=0.0, verbose_name='Новая цена (Если товар не на скидке, пожалуйста, укажите цену, равную обычной)')),
                ('Category', models.CharField(choices=[('1', 'Мягкая мебель'), ('2', 'Гостиная'), ('3', 'Спальня'), ('4', 'Кухня'), ('5', 'Столовая'), ('6', 'Прихожая'), ('7', 'Ванная'), ('8', 'Детская'), ('9', 'Рабочий кабинет')], default='Мягкая мебель', max_length=20, verbose_name='Категория')),
                ('image', models.ImageField(upload_to='', verbose_name='Главное фото (обязательно)')),
                ('image1', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Доп. фото (Необязательно)')),
                ('image2', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Доп. фото (Необязательно)')),
                ('image3', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Доп. фото (Необязательно)')),
                ('image4', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Доп. фото (Необязательно)')),
                ('image5', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Доп. фото (Необязательно)')),
                ('image6', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Доп. фото (Необязательно)')),
                ('image7', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Доп. фото (Необязательно)')),
                ('image8', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Доп. фото (Необязательно)')),
                ('inCollection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainpage.Collection', verbose_name='Коллекция')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.shops', verbose_name='Поставщик')),
            ],
        ),
    ]
