# Generated by Django 2.0.5 on 2018-05-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='Categoty',
            field=models.CharField(choices=[('1', 'Мягкая мебель'), ('2', 'Гостиная'), ('3', 'Спальня'), ('4', 'Кухня'), ('5', 'Столовая'), ('6', 'Прихожая'), ('7', 'Ванная'), ('8', 'Детская'), ('9', 'Рабочий кабинет')], default='Мягкая мебель', max_length=20, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
