# Generated by Django 2.0.5 on 2018-05-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='price',
            field=models.FloatField(default='0.00', max_length=10),
        ),
    ]
