# Generated by Django 2.0.5 on 2018-05-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180530_0209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopitem',
            old_name='Categoty',
            new_name='Category',
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='image1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='image2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='image3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='image4',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='image5',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='image6',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='image7',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='image8',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
