# Generated by Django 2.0.5 on 2018-05-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180530_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='price',
            field=models.CharField(default='0.00', max_length=10),
        ),
    ]
