# Generated by Django 2.0.5 on 2018-05-30 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180530_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='discounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nowprice', models.FloatField(verbose_name='Цена со скидкой')),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ShopItem')),
            ],
        ),
    ]
