# Generated by Django 2.0.5 on 2018-06-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20180531_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='newprice',
            field=models.FloatField(default=0.0, verbose_name='Новая цена'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='isdiscount',
            field=models.BooleanField(verbose_name='На свидке?'),
        ),
    ]
