# Generated by Django 2.0.5 on 2018-06-01 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20180601_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discounts',
            name='tovar',
        ),
        migrations.DeleteModel(
            name='discounts',
        ),
    ]
