# Generated by Django 2.0.5 on 2018-06-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20180601_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='newprice',
            field=models.FloatField(default=0.0, verbose_name='Новая цена (Если товар не на скидке, пожалуйста, укажите цену, равную обычной'),
        ),
    ]
