# Generated by Django 2.0.5 on 2018-06-01 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20180601_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='discriotion',
            field=models.TextField(verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='image1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Доп. фото (Необязательно)'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='image2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Доп. фото (Необязательно)'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='image3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Доп. фото (Необязательно)'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='image4',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Доп. фото (Необязательно)'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='image5',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Доп. фото (Необязательно)'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='image6',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Доп. фото (Необязательно)'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='image7',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Доп. фото (Необязательно)'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='image8',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Доп. фото (Необязательно)'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='inCollection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainpage.Collection'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='newprice',
            field=models.FloatField(default=0.0, verbose_name='Новая цена (Если товар не на скидке, пожалуйста, укажите цену, равную обычной)'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='subtitle',
            field=models.CharField(max_length=40, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Название товара'),
        ),
    ]
