# Generated by Django 2.0.5 on 2018-06-01 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20180601_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='inCollection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainpage.Collection', verbose_name='Коллекция'),
        ),
    ]
