# Generated by Django 2.0.5 on 2018-06-01 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20180601_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.shops', verbose_name='Поставщик'),
        ),
    ]
