# Generated by Django 2.0.5 on 2018-06-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20180601_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='qualities',
            field=models.TextField(default='крутая вещь', verbose_name='Характеристики'),
        ),
    ]
