# Generated by Django 2.0.5 on 2018-05-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Название товара', max_length=40, verbose_name='Название')),
                ('subtitle', models.CharField(default='Краткое описание', max_length=40, verbose_name='Краткое описание')),
                ('discriotion', models.TextField(default='Описание товара', verbose_name='Полное описание')),
                ('properties', models.TextField(default='(длина, ширина и т.д.)', verbose_name='Характеристики товара')),
                ('price', models.CharField(default='', max_length=10, verbose_name='Цена')),
                ('fullprice', models.CharField(default='', max_length=15, verbose_name='Полная цена без скидки')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('image1', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('image5', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('image6', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('image7', models.ImageField(blank=True, default=None, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Neme', max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('phone1', models.CharField(default='+375445106036', max_length=40)),
                ('phone2', models.CharField(default='+375445106036', max_length=40)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='slider1fill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='slider2fill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('discriotion', models.TextField()),
                ('nowprice', models.CharField(max_length=10)),
                ('prevprice', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='slider3fill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('discription', models.TextField()),
            ],
        ),
    ]
