# Generated by Django 2.0.5 on 2018-06-24 19:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Название товара', max_length=40, verbose_name='Название')),
                ('subtitle', models.CharField(default='Краткое описание', max_length=40, verbose_name='Краткое описание')),
                ('discriotion', models.TextField(default='Описание товара', verbose_name='Полное описание')),
                ('size', models.CharField(default='Не отображать', max_length=40, verbose_name='Размеры')),
                ('matherial', models.CharField(default='Не отображать', max_length=40, verbose_name='Материал')),
                ('color', models.CharField(default='Не отображать', max_length=40, verbose_name='Цвета')),
                ('qualities', models.TextField(default='Не отображать', verbose_name='Доп. характеристики')),
                ('price', models.FloatField(default='', max_length=10, verbose_name='Цена')),
                ('Category', models.CharField(choices=[('1', 'Мягкая мебель'), ('2', 'Гостиная'), ('3', 'Спальня'), ('4', 'Кухня'), ('5', 'Столовая'), ('6', 'Прихожая'), ('7', 'Ванная'), ('8', 'Детская'), ('9', 'Рабочий кабинет')], default='Мягкая мебель', max_length=20, verbose_name='Категория')),
                ('fullprice', models.CharField(default='', max_length=15, verbose_name='Полная цена без скидки')),
                ('image', models.ImageField(upload_to='')),
                ('image1', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('image5', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('image6', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('image7', models.ImageField(blank=True, default=None, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Заголовок новости')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка')),
                ('date', models.DateField(default=datetime.datetime(2018, 6, 24, 22, 37, 4, 241402), verbose_name='Дата')),
                ('discriotion', models.TextField(verbose_name='Текст новости')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Заголовок акции')),
                ('discriotion', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка')),
            ],
        ),
        migrations.CreateModel(
            name='shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Neme', max_length=40, verbose_name='Название')),
                ('discription', models.TextField(default='Описание магазина', verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Мини-логотип')),
                ('mainimage', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Полная картинка')),
                ('phone1', models.CharField(default='+375445106036', max_length=40, verbose_name='Телефон1')),
                ('worktime', models.CharField(default='Пн.-Пт.: ...', max_length=50, verbose_name='Время работы')),
                ('link', models.CharField(default='vegas.by', max_length=50, verbose_name='Ссылка на магазин')),
            ],
        ),
        migrations.CreateModel(
            name='slider1fill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('link', models.CharField(default='/catalog', max_length=100, verbose_name='Ссылка на товар либо новость')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainpage.shops'),
        ),
    ]
