# Generated by Django 2.0.5 on 2018-06-24 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='color',
            field=models.CharField(default=None, max_length=40, verbose_name='Цвета'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='matherial',
            field=models.CharField(default=None, max_length=40, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='qualities',
            field=models.TextField(default=None, verbose_name='Доп. характеристики'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='size',
            field=models.CharField(default=None, max_length=40, verbose_name='Размеры'),
        ),
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 24, 23, 8, 0, 60115), verbose_name='Дата'),
        ),
    ]
