# Generated by Django 2.0.5 on 2018-05-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider2fill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('discriotion', models.TextField()),
                ('nowprice', models.CharField(max_length=10)),
                ('prevprice', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='slider1fill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
