# Generated by Django 2.0.5 on 2018-05-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_collection_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='Category',
            field=models.CharField(choices=[('1', 'Мягкая мебель'), ('2', 'Гостиная'), ('3', 'Спальня'), ('4', 'Кухня'), ('5', 'Столовая'), ('6', 'Прихожая'), ('7', 'Ванная'), ('8', 'Детская'), ('9', 'Рабочий кабинет')], default='Мягкая мебель', max_length=20, verbose_name='Категория'),
        ),
    ]
