# Generated by Django 2.0.5 on 2018-05-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20180518_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider3fill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('discription', models.TextField()),
            ],
        ),
    ]
