# Generated by Django 2.0.5 on 2018-06-24 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20180624_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 24, 23, 8, 36, 925612), verbose_name='Дата'),
        ),
    ]
