# Generated by Django 2.0.5 on 2018-05-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_shops'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='phone1',
            field=models.CharField(default='+375445106036', max_length=40),
        ),
        migrations.AddField(
            model_name='shops',
            name='phone2',
            field=models.CharField(default='+375445106036', max_length=40),
        ),
        migrations.AddField(
            model_name='shops',
            name='title',
            field=models.CharField(default='Neme', max_length=40),
        ),
    ]
