# Generated by Django 2.0.5 on 2018-06-25 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_auto_20180625_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 25, 17, 41, 57, 485785), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='phone2',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Телефон2 (необязательно)'),
        ),
    ]
