# Generated by Django 2.0.5 on 2018-05-30 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_shops_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='price',
            field=models.FloatField(default='', max_length=10, verbose_name='Цена'),
        ),
    ]
