# Generated by Django 2.0.5 on 2018-06-02 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 2, 16, 27, 18, 740467)),
        ),
    ]
