# Generated by Django 2.0.5 on 2018-06-02 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_new_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='slider2fill',
        ),
        migrations.DeleteModel(
            name='slider3fill',
        ),
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 2, 16, 32, 15, 933791)),
        ),
    ]
