# Generated by Django 2.0.5 on 2018-06-02 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_auto_20180602_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 2, 16, 33, 44, 930498), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discriotion',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Заголовок акции'),
        ),
    ]
