# Generated by Django 2.0.5 on 2018-06-06 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0012_auto_20180602_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 6, 15, 37, 1, 540686), verbose_name='Дата'),
        ),
    ]
