# Generated by Django 2.0.5 on 2018-06-06 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0013_auto_20180606_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='properties',
        ),
        migrations.AddField(
            model_name='collection',
            name='qualities',
            field=models.TextField(default='крутая вещь', verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 6, 16, 1, 12, 588806), verbose_name='Дата'),
        ),
    ]
