# Generated by Django 2.0.5 on 2018-06-06 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0014_auto_20180606_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider1fill',
            name='link',
            field=models.CharField(default='/catalog', max_length=100, verbose_name='Ссылка на товар либо новость'),
        ),
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 6, 16, 4, 39, 353864), verbose_name='Дата'),
        ),
    ]
